name: Jekyll site CI

on:
  push:
    branches: [ master-xpert ]
  pull_request:
    branches: [ master-xpert ]

jobs:
  robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Requirements
        run: |
          pip install -r requirements.txt
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v0.1
        env:
          BROWSER: chrome
          ROBOT_TESTS_DIR: ${{ github.workspace }}/Web/bodytest/tests/
#          ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports
