# This is a basic workflow to help you get started with Actions

name: CI-Xpert

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master-xpert branch
  push:
    branches: [ master-xpert ]
  pull_request:
    branches: [ master-xpert ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build
          echo test, and deploy your project
          echo curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
          echo apt-get install -y nodejs
          echo pip install -r requirements.txt
          echo rfbrowser init
          echo robot -d ./log Web/bodytest/tests/
          

